spring.application.name=gestion_producto

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_producto
spring.datasource.username=root
spring.datasource.password=Mmcode1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true